### ISSUE TITLE
Channels with empty messages

### ISSUE THREAD

**Issue by Wessel93** [rodekruis/rumor-tracker#19]
Some channels only return empty messages (Romania-> UkrainiansinRomania) while the group in telegram actually shows messages. Steps to take:

- Check Telegram API rules why message content is not send -> privacy settings of channel?
- Check for which channels this holds
- Remove channels?

**Comment by p-phung** [comment]
![Image](https://user-images.githubusercontent.com/45565029/215100333-1e56ef30-3b20-41a2-8a36-6d6548857364.png)

**Comment by p-phung** [comment]
__Findings:__
- No message match the post time (the column datetime in the screenshot above). It might be that the messages were removed. The scraper can see the "message item" but the message content is not there anymore. That's why it returns "None".
- The case of the group "UkrainiansinRomania" (Romania) is different where the messages shown in the file are completely empty. It is because the group only allows approved members to read their messages and our scraper are not considered as an "approved member".

__Solutions:__
